// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyStage struct {
	Date      pgtype.Date        `json:"date"`
	StageID   int32              `json:"stage_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Stage struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
