// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignStageToDate = `-- name: AssignStageToDate :exec
INSERT INTO daily_stages (date, stage_id) VALUES ($1, $2)
ON CONFLICT (date) DO UPDATE SET stage_id = EXCLUDED.stage_id
`

type AssignStageToDateParams struct {
	Date    pgtype.Date `json:"date"`
	StageID int32       `json:"stage_id"`
}

func (q *Queries) AssignStageToDate(ctx context.Context, arg AssignStageToDateParams) error {
	_, err := q.db.Exec(ctx, assignStageToDate, arg.Date, arg.StageID)
	return err
}

const createStage = `-- name: CreateStage :one
INSERT INTO stages (name, data) VALUES ($1, $2) RETURNING id, name, data, created_at, updated_at
`

type CreateStageParams struct {
	Name string `json:"name"`
	Data []byte `json:"data"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage, arg.Name, arg.Data)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE FROM stages WHERE id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStage, id)
	return err
}

const getStage = `-- name: GetStage :one
SELECT id, name, data, created_at, updated_at FROM stages WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id int32) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStageByDate = `-- name: GetStageByDate :one
SELECT s.id, s.name, s.data, s.created_at, s.updated_at FROM stages s
JOIN daily_stages ds ON ds.stage_id = s.id
WHERE ds.date = $1
`

func (q *Queries) GetStageByDate(ctx context.Context, date pgtype.Date) (Stage, error) {
	row := q.db.QueryRow(ctx, getStageByDate, date)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodayStage = `-- name: GetTodayStage :one
SELECT s.id, s.name, s.data, s.created_at, s.updated_at FROM stages s
JOIN daily_stages ds ON ds.stage_id = s.id
WHERE ds.date = CURRENT_DATE
`

func (q *Queries) GetTodayStage(ctx context.Context) (Stage, error) {
	row := q.db.QueryRow(ctx, getTodayStage)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedule = `-- name: ListSchedule :many
SELECT ds.date, ds.stage_id, s.name
FROM daily_stages ds
JOIN stages s ON s.id = ds.stage_id
ORDER BY ds.date
`

type ListScheduleRow struct {
	Date    pgtype.Date `json:"date"`
	StageID int32       `json:"stage_id"`
	Name    string      `json:"name"`
}

func (q *Queries) ListSchedule(ctx context.Context) ([]ListScheduleRow, error) {
	rows, err := q.db.Query(ctx, listSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleRow
	for rows.Next() {
		var i ListScheduleRow
		if err := rows.Scan(&i.Date, &i.StageID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStages = `-- name: ListStages :many
SELECT id, name, created_at, updated_at FROM stages ORDER BY id
`

type ListStagesRow struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStages(ctx context.Context) ([]ListStagesRow, error) {
	rows, err := q.db.Query(ctx, listStages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStagesRow
	for rows.Next() {
		var i ListStagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignDate = `-- name: UnassignDate :exec
DELETE FROM daily_stages WHERE date = $1
`

func (q *Queries) UnassignDate(ctx context.Context, date pgtype.Date) error {
	_, err := q.db.Exec(ctx, unassignDate, date)
	return err
}

const updateStage = `-- name: UpdateStage :one
UPDATE stages SET name = $2, data = $3, updated_at = NOW() WHERE id = $1 RETURNING id, name, data, created_at, updated_at
`

type UpdateStageParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Data []byte `json:"data"`
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, updateStage, arg.ID, arg.Name, arg.Data)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
